host: 0.0.0.0
title: Pears & Stuff
email: figgchristian@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Awesome Pears and Stuff Website :D
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pearsandstuff.com" # the base hostname & protocol for your site, e.g. http://example.com


# Build settings
theme: minima
plugins:
  - jekyll-feed